version: '3'

services:
  healthcheck:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:5000"
  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: qowerty123
      POSTFRES_DB: Lab3