version: '3'

services:
  healthcheck:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
     DB_USER: "postgres"
     DB_PASSWORD: "qowerty123"
     DB_HOST: "db:5432"
     DB_NAME: "postgres"
   ports:
     - "5000:5000"
  db:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: "qowerty123"
    ports:
      - "5432:5432"